class Languages:
    def __init__(self):
        self.languages = {
            "en": "English",
            "es": "Spanish",
            "fr": "French",
            "de": "German",
            "it": "Italian",
            "nl": "Dutch",
            "ru": "Russian",
            "ja": "Japanese",
            "zh-CN": "Chinese (Simplified)",
            "zh-TW": "Chinese (Traditional)",
            "ar": "Arabic",
            "fa": "Persian",
            "he": "Hebrew",
            "hi": "Hindi",
            "id": "Indonesian",
            "ko": "Korean",
            "pt": "Portuguese",
            "sv": "Swedish",
            "tr": "Turkish",
            "uk": "Ukrainian",
            "vi": "Vietnamese",
            "el": "Greek",
            "pl": "Polish",
            "ro": "Romanian",
            "hu": "Hungarian",
        }
